### ISSUE TITLE
Record toggle on/off

### ISSUE THREAD

**Issue by HYP-Electric** [Hypest-team/HypestBoard#10]
Have a Record toggle show on preview/source when we are recording or not 

(Red screen or whatever when its recording and Black or Blue or something when we're not)

**Comment by N0NamedGuy** [comment]
I believe that goes a bit beyond the scope of the software.
It needs some kind of interaction with OBS/XSplit to know if it is streaming recording, or/and integrate with Twitch to know if it is streaming or not.

EDIT: I misunderstood the original request. Lack of sleep and all that....
So, after moving into a webapp, it would be possible to add an embedable of the twitch stream, just like StreamKoala (https://skhmt.github.io/koala2/).

**Comment by N0NamedGuy** [comment]
After having a long thought, nope, not implementing this one.
