### ISSUE TITLE
Edit moobot from webUI

### ISSUE THREAD

**Issue by HYP-Electric** [Hypest-team/HypestBoard#11]
Ability to edit functionalities like !bracket , !follow and so on from our webUI . Maybe not needed but would be easier to have a sort of all in one or a toggle to go to bot functionalities and so stuff from there. (Because knowing myself I could forget or I can also ask future moderators to take care of that)

**Comment by N0NamedGuy** [comment]
I believe that would be a better fit for a separate project. If such project exists, or is done, we can integrate both... Will leave this one open for now. Need to reflect on this one.

**Comment by N0NamedGuy** [comment]
I will mark this one as wontfix, and close it. May reopen in the future, but I doubt I will be able to implement this one. Let's wait for the codebase to stabilize and then we can reconsider this feature.
