### ISSUE TITLE
Swap feature in doubles

### ISSUE THREAD

**Issue by HYP-Electric** [Hypest-team/HypestBoard#14]
Need to be able to swap names within the same team to make sure order matches with each character 

(Swap teams and swap players names in the team)

**Comment by N0NamedGuy** [comment]
Yes, that makes sense... Should be minor.

**Comment by HYP-Electric** [comment]
major* :P it's really important to have that!

**Comment by N0NamedGuy** [comment]
Minor is not priority. Priority is not sorted. It is just effort required on implementation.
Prioritization will be done whenever I have good number of issues. After that we create milestones, and set which issues should be tackled. THAT is prioritization 😃

**Comment by N0NamedGuy** [comment]
This issue is kinda related to #19

**Comment by N0NamedGuy** [comment]
Done
