### ISSUE TITLE
"-" not transferring from Local MP4 title to Youtube

### ISSUE THREAD

**Issue by HYP-Electric** [Hypest-team/HypestBoard#15]
the symbol " - " is not transferring from the titles to when uploading on youtube 

IE

Local title:   " Hypest Team Monthly 1 - Dynastyle Vs Sticker - Winners Semis - Smash 4 Singles " 

Translates on Youtube to:  " Hypest Team Monthly 1  Dynastyle Vs Sticker  Winners Semis  Smash 4 Singles"

Need to find a fix else we spend ages adding dumb " - " on titles, making them look weird for viewers.

**Comment by HYP-Electric** [comment]
(Also a problem for people who have names separated with " - " such as L-t  becomes L t)

**Comment by N0NamedGuy** [comment]
This has nothing to do with the overlay project.
